import re
import ast

file_path = r'c:\Users\paula\Documents\mgr pjatk\streamlit_app.py'
with open(file_path, 'r', encoding='utf-8') as f:
    content = f.read()

# Extract the PL dict string
match = re.search(r'PL = (\{.*?\n\})', content, re.DOTALL)
if not match:
    print("PL dict not found.")
    exit(1)

pl_str = match.group(1)
PL = ast.literal_eval(pl_str)

new_PL = {}
for k, v in PL.items():
    new_PL[k] = v  # Default to current value

# Apply transformations
replacements = {
    "AAC Adoption Thesis Demo": "Wizualizacja wyników pracy magisterskiej: analiza predykcyjna adopcji w AAC",
    "Artifact-driven dashboard for model results, hypothesis signals, and model sensitivity checks.": "Interaktywny system wizualizacji modeli klasyfikacyjnych, weryfikacji hipotez oraz analizy wrażliwości.",
    "Executive Overview": "Przegląd analityczny",
    "Story Mode": "Analiza ścieżek (Story Mode)",
    "Animal Stories": "Analiza przypadków (Case Studies)",
    "Model Quality": "Ewaluacja predykcyjna modelu",
    "Trust & Limits": "Analiza wiarygodności i ograniczeń",
    "Interpretability": "Interpretowalność (XAI)",
    "Risk Explorer": "Moduł ewaluacji ryzyka",
    "Hypothesis Lab": "Weryfikacja hipotez badawczych",
    "Campaign Finder": "Identyfikacja celów interwencji promocyjnych",
    "Adoption Timeline": "Analiza przeżycia (Oś czasu adopcji)",
    "Artifacts": "Zestawienie artefaktów badawczych",
    "Context Data": "Zmienne środowiskowe i kontekstowe",
    "Run the training and analysis pipeline to populate model comparison outputs.": "Uruchom potok trenowania i analizy (pipeline), aby wygenerować wyniki porównawcze modeli.",
    "Missing figure": "Brakujący artefakt graficzny",
    "Data-to-Decision Story": "Transformacja danych w sygnały decyzyjne",
    "How raw shelter records become thesis evidence and practical shelter-facing signals.": "Proces transformacji surowych danych schroniskowych w empiryczny materiał badawczy oraz analityczne sygnały decyzyjne.",
    "Approach Comparison": "Analiza porównawcza podejść analitycznych",
    "Analytical layer": "Warstwa analityczna",
    "Story weight": "Waga przypadku",
    "Probability Trust": "Kalibracja i wiarygodność predykcji",
    "When model says 70% adoption chance, does reality agree?": "Weryfikacja stopnia zgodności prognozowanego prawdopodobieństwa adopcji z rzeczywistą częstością zdarzeń.",
    "Calibration curve": "Krzywa kalibracyjna (Reliability Diagram)",
    "Long-stay Risk": "Estymacja ryzyka wydłużonego pobytu",
    "Which animals look adoptable but may wait longer?": "Identyfikacja kohort o wysokim prawdopodobieństwie adopcji przy jednoczesnym podwyższonym ryzyku wydłużonego czasu oczekiwania.",
    "Model Failure Modes": "Charakterystyka błędów modelu (Failure Modes)",
    "Where do false negatives and large LOS errors cluster?": "Identyfikacja klastrów fałszywie negatywnych predykcji oraz wariancji w estymacji czasu pobytu.",
    "Which cohorts may deserve targeted visibility?": "Identyfikacja subpopulacji wymagających ukierunkowanych działań promocyjnych.",
    "Similar Cases": "Analiza historycznych przypadków referencyjnych",
    "What happened historically to animals like this one?": "Analiza rozkładu wyników dla historycznych wektorów o wysokim stopniu prawdopodobieństwa/podobieństwa.",
    "Real-life Shelter Questions": "Zastosowanie operacyjne w warunkach schroniskowych",
    "Animal Journey Cards": "Karty analizy ścieżki pobytu",
    "Run `python scripts/generate_animal_research.py --data data/processed/modeling_dataset.csv` to populate animal stories.": "Uruchom `python scripts/generate_animal_research.py --data data/processed/modeling_dataset.csv`, aby wygenerować analizę przypadków zwierząt.",
    "Animal profile": "Profil analizowanego obiektu",
    "Similar records": "Zbieżne wektory (N)",
    "Adoption rate": "Odsetek pozytywnych adopcji (%)",
    "Median days to outcome": "Mediana czasu do rozstrzygnięcia (dni)",
    "Visibility need": "Ewaluacja potrzeby ekspozycji",
    "Profile": "Charakterystyka obiektu",
    "has recorded name": "zarejestrowane imię",
    "no recorded name": "brak zarejestrowanego imienia",
    "Transfer rate": "Odsetek transferów zewnętrznych (%)",
    "Return-to-owner rate": "Odsetek powrotów do pierwotnego właściciela (%)",
    "Euthanasia rate": "Wskaźnik eutanazji (%)",
    "Model View for This Journey": "Wynik predykcji dla zadanego wektora",
    "Run `python scripts/train_advanced.py --data data/processed/modeling_dataset.csv` to add representative CatBoost predictions to journey cards.": "Uruchom `python scripts/train_advanced.py --data data/processed/modeling_dataset.csv`, aby włączyć ewaluację modelem CatBoost do widoku profili.",
    "Predicted adoption chance": "Estymowane prawdopodobieństwo adopcji",
    "Predicted wait": "Estymowany czas oczekiwania",
    "Predicted Time to Any Outcome": "Estymowany czas do rozstrzygnięcia",
    "Model visibility label": "Klasyfikacja zapotrzebowania na ekspozycję",
    "Length-of-stay bucket": "Kategoryzacja estymowanej długości pobytu",
    "Representative model record": "Referencyjny wektor cech w modelu",
    "high visibility need": "wysoki priorytet ekspozycji",
    "medium visibility need": "umiarkowany priorytet ekspozycji",
    "standard visibility": "standardowy priorytet ekspozycji",
    "low": "niska",
    "medium": "umiarkowana",
    "high": "wysoka",
    "Similar Historical Cases": "Historyczne profile referencyjne",
    "No similar historical cases found for this representative card.": "Brak historycznych obserwacji o wystarczającym stopniu zbieżności cech dla analizowanego wektora.",
    "Top SHAP Reasons": "Analiza istotności cech lokalnych (SHAP)",
    "Run `python scripts/generate_diagnostics.py --data data/processed/modeling_dataset.csv --include-shap` to populate SHAP reasons.": "Uruchom `python scripts/generate_diagnostics.py --data data/processed/modeling_dataset.csv --include-shap`, aby wygenerować wektory wartości SHAP.",
    "Model-wide SHAP signals mapped onto this animal profile; associations, not causes.": "Globalne wartości dyskryminacyjne (SHAP) aproksymowane dla analizowanego wektora; wskazują korelacje, bez implikacji kauzalnych.",
    "Local CatBoost SHAP values for the representative journey record; associations, not causes.": "Lokalne miary SHAP (CatBoost) dla analizowanego wektora; determinują asocjacje bez domniemania związków przyczynowo-skutkowych.",
    "Key Animal Contrasts": "Kluczowe dysproporcje statystyczne",
    "Contrast": "Rozbieżność (Contrast)",
    "Animal group": "Kategoria podmiotu",
    "Largest animal archetypes": "Dominujące klastry fenotypowe",
    "Animal profiles needing visibility or support": "Profile wymagające podwyższonej ekspozycji lub specjalistycznego wsparcia",
    "Vulnerable Profiles": "Kohorty o podwyższonym poziomie ryzyka (Vulnerable)",
    "Health and Behavior Support Profiles": "Profile specyficznych interwencji medycznych i behawioralnych",
    "Classification Table": "Macierz wyników klasyfikacyjnych",
    "Regression Table": "Macierz błędów regresyjnych",
    "Probability Trust Meter": "Analiza wiarygodności (Calibration / Trust)",
    "Run `python scripts/generate_diagnostics.py --data data/processed/modeling_dataset.csv` to populate calibration diagnostics.": "Uruchom `python scripts/generate_diagnostics.py --data data/processed/modeling_dataset.csv`, aby wyliczyć metryki kalibracyjne.",
    "Mean predicted probability": "Średnie estymowane prawdopodobieństwo",
    "Observed adoption rate": "Empiryczny odsetek adopcji",
    "Reliability Figures": "Wizualizacja charakterystyk niezawodności",
    "Advanced model ROC curve": "Krzywa ROC (Receiver Operating Characteristic) modelu docelowego",
    "Advanced model precision-recall curve": "Krzywa PR (Precision-Recall) modelu docelowego",
    "Probability calibration": "Krzywa kalibracji prawdopodobieństw (Reliability Curve)",
    "Regression predicted vs actual": "Analiza wariancji: przewidywania regresora a wartości empiryczne",
    "Model Evidence Pack": "Rozszerzone dossier ewaluacji modelu",
    "Run `python scripts/generate_evidence_pack.py --data data/processed/modeling_dataset.csv` to populate trust and limits artifacts.": "Uruchom `python scripts/generate_evidence_pack.py --data data/processed/modeling_dataset.csv`, aby wygenerować estymatory zaufania analitycznego.",
    "Metric Confidence Intervals": "Przedziały ufności dla metryk ewaluacyjnych",
    "Metric": "Metryka",
    "Bootstrap interval": "Estymator przedziałowy (Bootstrap CI)",
    "Cohort Reliability Limits": "Analiza pogorszenia parametrów predykcyjnych w subpopulacjach",
    "Calibration gap": "Błąd kalibracji (Calibration Gap)",
    "Cohort value": "Kwantyfikacja dla subpopulacji",
    "Subgroup Explorer": "Dekonstrukcja metryk w subpopulacjach",
    "Reliability subgroup": "Rozpatrywana podgrupa demograficzna",
    "Where the Model Struggles": "Obszary ograniczonej zdolności predykcyjnej",
    "Subgroup Metric Intervals": "Analiza przedziałowa metryk podgrup",
    "Time-to-Adoption Milestones": "Punkty krytyczne czasu przebywania w schronisku",
    "Milestone subgroup": "Podgrupa ewaluowana (Survival Analysis)",
    "Adopted animals (%)": "Skumulowany odsetek adopcji (%)",
    "Milestone": "Kwantyl czasowy",
    "Value": "Miara empiryczna",
    "Records": "Liczba obserwacji (N)",
    "Adoptions": "Zrealizowane adopcje",
    "Adopted by day": "Rozstrzygnięte do (dzień)",
    "Animal Journey Evidence Examples": "Empiryczna weryfikacja predykcji na tle przypadków historycznych",
    "SHAP Global Explanations": "Globalna analiza struktury ważności cech (SHAP)",
    "SHAP values describe factors associated with model predictions, not causal effects.": "Miary SHAP kwantyfikują relacyjną istotność predyktorów; nie uprawniają one do konkluzji o mechanizmach przyczynowo-skutkowych.",
    "Classification SHAP summary": "Struktura ważności predyktorów: model klasyfikacyjny",
    "Regression SHAP summary": "Struktura ważności predyktorów: model regresyjny",
    "Feature Family Scores": "Znaczenie predykcyjne zagregowanych klas cech",
    "Sum mean absolute SHAP": "Zsumowana bezwzględna wartość aproksymacji SHAP",
    "Feature family": "Kategoria predyktorów",
    "Run diagnostics with `--include-shap` to populate interpretation artifacts.": "Zainicjuj system z parametrem `--include-shap` dla pełnej dekompozycji XAI.",
    "Risk Threshold Simulator": "Analiza wrażliwości na przesunięcie progu klasyfikacyjnego (Decision Threshold Simulator)",
    "Run diagnostics to populate threshold tradeoffs.": "Uruchom rutyny diagnostyczne w celu wygenerowania punktów kompromisu (trade-off) dla progu.",
    "Adoption probability threshold": "Próg prawdopodobieństwa dyskryminacji pozytywnej",
    "Precision": "Precyzja predykcji (Precision)",
    "Recall": "Czułość predykcji (Recall)",
    "F1": "Metryka harmonijna (F1 Score)",
    "Flagged share": "Frakcja obserwacji zakwalifikowanych ponad próg",
    "Threshold": "Próg decyzyjny",
    "Metric value": "Kwantyfikacja metryki",
    "Placement Risk Quadrant": "Macierz identyfikacji przypadków o podwyższonym ryzyku przedłużonego pobytu",
    "Predicted adoption probability": "Estymowane prawdopodobieństwo sukcesu adopcyjnego",
    "Predicted days to outcome": "Estymowany czas przetrzymywania do rozstrzygnięcia",
    "Error Slice Explorer": "Dekompozycja strukturalna błędu estymatora",
    "H1: Intake vs Appearance": "H1: Zmienne kontekstowe vs predyktory fenotypowe",
    "H3: Age and Length of Stay": "H3: Dystrybucja czasu pobytu w funkcji wieku",
    "H5: COVID-period Dynamics": "H5: Oscylacje wolumenu zjawiska w okresie pandemii COVID-19",
    "Campaign Candidate Finder": "Moduł selekcji kohortowej dla ukierunkowanych interwencji promocyjnych",
    "Exploratory cohort finder for groups that may benefit from targeted visibility. This is not causal recommendation logic.": "Eksploracyjne narzędzie identyfikacji podgrup o zaniżonym profilu adopcyjnym. Wyselekcjonowane podmioty pełnią rolę propozycji decyzyjnej bez domniemania deterministycznej sprawczości kampanii.",
    "Run diagnostics to populate campaign cohorts.": "Dokonaj ewaluacji diagnostycznej, aby wypełnić macierz pre-wytypowanych grup promocyjnych.",
    "All": "Populacja całkowita",
    "No records match this cohort.": "Nie zidentyfikowano wektorów spełniających warunki definicji wybranej kohorty.",
    "Cohort size": "Liczebność (N) podgrupy",
    "Observed adoption": "Wskaźnik adopcji - obserwacje empiryczne",
    "Mean predicted adoption": "Wartość oczekiwana estymowanego prawdopodobieństwa",
    "Median predicted days": "Mediana prognozowanego czasu przetrzymywania (dni)",
    "Campaign framing: this cohort may be useful for targeted visibility when predicted adoption probability is low or predicted days to outcome are high. Treat this as a prioritization signal, not proof of intervention impact.": "Założenia operacyjne: wyszczególniona kohorta kwalifikuje się do objęcia zintensyfikowanym pakietem ekspozycji, ze względu na deficyt przewidywanego prawdopodobieństwa i/lub znacząco wydłużony prognozowany czas pobytu. Wynik ma charakter wspierający, a nie kauzalnie gwarantujący zwiększoną odnajdywalność (findability).",
    "Animal Type": "Gatunek",
    "Age Group": "Kategoria ontogenetyczna (Wiek)",
    "Intake Type": "Charakterystyka trybu przyjęcia",
    "Covid Period": "Dychotomia dla reżimu COVID-19",
    "Uses the combined CatBoost classifier and regressor when advanced artifacts exist. This is a demo prediction, not a causal decision rule.": "Wykorzystuje agregację estymatorów (klasyfikator i regresor algorytmu CatBoost). Mechanizm predykcji odgrywa rolę demonstracyjną i nie powinien być traktowany jako autonomiczna funkcja rozstrzygająca.",
    "Animal type": "Gatunek",
    "Intake type": "Klasyfikacja formalna trybu przyjęcia",
    "Intake condition": "Stan kondycyjno-zdrowotny przy inkorporacji",
    "Sex upon intake": "Status reprodukcyjny zwierzęcia w chwili inkorporacji",
    "Has name": "Identyfikator nadany (Imię)",
    "Age in years": "Zmienna ciągła wieku (lata)",
    "Breed": "Taksonomia rasy",
    "Color": "Klasyfikacja fenotypowa umaszczenia",
    "Intake date": "Temporalny znacznik przyjęcia",
    "Run prediction": "Zainicjuj predykcję heurystyczną",
    "Run `python scripts/train_advanced.py --data data/processed/modeling_dataset.csv` first.": "Czynność uzależniona od wykonania komendy bazowej: `python scripts/train_advanced.py --data data/processed/modeling_dataset.csv`.",
    "Timeline group": "Agregacja temporalna",
    "Run diagnostics to generate adoption timeline milestones.": "Przetwórz zadania diagnostyczne by zdefiniować dystrybuantę (tzw. kamienie milowe) adopcji.",
    "Share adopted (%)": "Poziom stopnia adopcji (%)",
    "Adoption timeline milestones": "Wyznaczniki temporalne czasu do zwolnienia schroniskowego",
    "Generated Artifacts": "Repozytorium wygenerowanych rezultatów analitycznych",
    "Core commands:": "Dyspozycje krytyczne (Core Commands):",
    "Reports directory:": "Lokalizacja wyników tekstowych (Reports):",
    "Models directory:": "Lokalizacja sieci oraz artefaktów modeli (Models):",
    "External Context Feature Test": "Test predykcyjności skompresowanych zmiennych środowiskowych",
    "Run the commands below to populate `context_model_comparison.csv`.": "Użyj zaprezentowanych komend dla zaludnienia pliku `context_model_comparison.csv`.",
    "Context features use intake-date weather and prior-window 311/intake-volume counts only.": "Wymiar zmiennych kontekstowych redukuje się do logarytmicznie przetworzonych wektorów wolumenowych, raportów interwencyjnych (z systemu 311) oraz profili atmosferycznych w momentach krańcowych inkorporacji.",
    "Context minus base metric delta": "Zmienność różniczkowa z zastosowaniem kontroli kontekstowych a podejściem zero-komponentowym (Base)",
    "Model": "Paradygmat optymalizacyjny",
    "Effect": "Wariancja wyniku",
    "Task": "Zadana architektura (Task)",
    "improved": "wzmocnienie predykcyjności",
    "worsened": "degradacja jakości estymatora",
    "Dog": "Pies",
    "Cat": "Kot",
    "Stray": "Obiekt porzucony/bezpański (Stray)",
    "Owner Surrender": "Przekazanie na własność od dotychczasowego prawnego opiekuna",
    "Public Assist": "Pozyskanie w asyście służb państwowych",
    "Abandoned": "Obiekt zarejestrowany jako porzucony",
    "Euthanasia Request": "Protokół przyjęcia eutanazyjnego (Request)",
    "Normal": "Normatywny (Normalny)",
    "Injured": "Wybitnie urazowy (Ranny)",
    "Sick": "Wybitnie chorobowy (Chory)",
    "Nursing": "Status laktacyjny (Karmiący/a)",
    "Neonatal": "Przedwcześnie odłączony/Noworodek (Neonatalny)",
    "Aged": "Wybitnie podeszły wiek (Geriatryczny)",
    "Medical": "O podwyższonych kryteriach asysty medycznej",
    "Behavior": "O specyficznych ograniczeniach behawioralnych",
    "Other": "Kategoria marginalizowana (Inna)",
    "Intact Male": "Samiec niezdezintegrowany reprodukcyjnie",
    "Intact Female": "Samica niezdezintegrowana reprodukcyjnie",
    "Neutered Male": "Samiec pozbawiony zdolności reprodukcyjnych (Kastrat)",
    "Spayed Female": "Samica pozbawiona zdolności reprodukcyjnych (Wysterylizowana)",
    "Unknown": "Kwantyfikator nierozpoznany (Unknown)",
    "unknown health": "Aspekt zdrowotny nieoznaczony",
    "unknown behavior signal": "Atrybut behawioralny niezakwalifikowany",
    "📖 Thesis Guide": "Struktura manuskryptu oraz mapowanie referencji",
    "Model Sensitivity Demo": "Moduł empirycznej ewaluacji podatności na wejście (Sensitivity Analysis)",
    "Filter by Required for Thesis": "Filtruj względem zbioru rezultatów obligatoryjnych",
    "Select Report to View": "Dekompozycja jednostkowego sprawozdania ewaluacyjnego",
    "Viewing Report:": "Aktualna wizualizacja pliku:",
    "Report file not found on disk.": "Zgłoszono brak fizycznego pliku artefaktu analitycznego.",
    "Target Definitions & Outcome Mappings": "Aksjomatyczne definicje wskaźników celu a macierze alokacji rezultatów",
    "External Causal Validity & Generalisation Limits": "Wiarygodność w sensie zewnętrznym a restrykcje generalizacji (Ograniczenia wnioskowania przyczynowo-skutkowego)",
    "Breed and Coat Colour Feature Engineering Justification": "Prakseologiczne uzasadnienie konstrukcji wyestrahowanych atrybutów morfologicznych (rasa, maść)",
    "Machine Learning vs. Descriptive Non-ML Baselines": "Dystynkcja rozwiązań Machine Learning (ML) na tle algorytmów bez modelu ukrytego (Baseline)",
    "H1 — Intake Profile & Causal Context": "H1 — Walidacja profilu okoliczności początkowych przy przyjęciu",
    "H2 — Seasonality & Intake Dynamics": "H2 — Rozpoznanie fluktuacji w wymiarze sezonowym i strukturalnym wolumenu",
    "H3 — Age and Time-to-Outcome Timing": "H3 — Kryterium ontogenetyczne a modelowanie estymaty czasu deinkorporacji (Time-to-Outcome)",
    "H4 — Coat Colour (Black/Dark Animal Syndrome Check)": "H4 — Test obciążenia zjawiskiem tzw. 'Black/Dark Animal Syndrome'",
    "H5 — COVID-Period Population Shift and Volume Impact": "H5 — Wpływ wstrząsu pandemicznego na strukturę agregatów ewidencji",
    "H1 - Intake Profile & Causal Context": "H1 - Profil okoliczności początkowych przy przyjęciu",
    "H2 - Seasonality & Intake Dynamics": "H2 - Fluktuacje w wymiarze sezonowym i strukturalnym",
    "H3 - Age and Time-to-Outcome Timing": "H3 - Modelowanie estymaty czasu deinkorporacji",
    "H4 - Coat Colour (Black/Dark Animal Syndrome Check)": "H4 - Test 'Black/Dark Animal Syndrome'",
    "H5 - COVID-Period Population Shift and Volume Impact": "H5 - Wpływ szoku pandemicznego",
    "Hypothesis Evidence Matrix Summary": "Wielowymiarowa macierz pokrycia weryfikacyjnego badanych hipotez",
    "Data Leakage Audit & Control Log": "Ścisły dziennik ochrony spójności sekwencyjnej (Data Leakage Log)",
    "Propensity Score Matching Validation Examples": "Dokumentacja estymatora równoważności prawdopodobieństw (Propensity Score Matching)",
    "Narrative Model Evidence & Key Findings Pack": "Podstawowy wyciąg sprawozdawczo-deskryptywny",
    "Subgroup Reliability & Underrepresented Cohorts": "Rejestr parametrów stabilności subpopulacji zjawiskowych i słabo wyeksponowanych",
    "Final Model Architecture Selection": "Argumentacja procesu selekcyjnego docelowej struktury algorytmicznej",
    "Optimal Classification Threshold & Utility Analysis": "Matematyczna wycena poziomu kompromisu (Optimal Decision Boundary)",
    "Model Probability Calibration Interpretation": "Przełożenie fizyczne skategoryzowanych rozkładów wiarygodności modelu",
    "Operational Risk & Model Reliability Red Flags": "Metryki zagrożenia stabilności wykonawczej z odnotowaniem tzw. Red Flags",
    "Data Pipeline Audit & Attrition Logging": "Log procesów potoku analitycznego włączając odsetek utraty informacji na stadiach konwersji (Attrition Logging)",
    "Reproducibility Snapshot & Environment Info": "Wektor ewaluacji stabilności i spójności konfiguracyjnej ekosystemu",
    "quick placement likely": "przewidywana bezzwłoczna relokacja docelowa",
    "needs visibility": "konieczność amplifikacji ekspozycji (Promocja)",
    "long-stay risk": "obciążony znacznym stopniem ryzyka zamrożenia stanu",
    "outcome support priority": "sygnalizowany tryb wsparcia pozaobszarowego (Priorytet decyzyjny)",
    "Classification PR-AUC": "Obszar pod krzywą PR (Precision-Recall AUC) na modelu klasyfikującym",
    "Classification ROC-AUC": "Obszar pod krzywą ROC (Receiver Operating Characteristic) dla klasyfikacji",
    "Classification F1": "Wartość harmoniczna błędu uśrednionego (F1-score)",
    "Regression MAE": "Średni moduł błędu absolutnego (MAE) dla regresji",
    "Regression RMSE": "Pierwiastek błędu średniokwadratowego (RMSE)",
    "Predicted adoption chance (calibrated)": "Zrekalibrowana estymata prawdopodobieństwa sukcesu adopcyjnego",
    "Predicted adoption probability (calibrated)": "Ujednolicone kalibracyjnie prawdopodobieństwo dyskryminacji",
    "**Adoption Rates by Intake Type**": "**Ewaluacja stopnia sprawności procesu adopcyjnego w warunkach klasyfikacji startowej**",
    "**Finding:** Older animals face significant penalties in adoption likelihood. Wait times to any outcome are complex, as seniors may leave the shelter faster due to higher rates of non-adoption outcomes.": "**Postulat dedukcyjny:** Znaczący spadek współczynników weryfikujących pozytywne rezultaty adopcyjne ujawniono w odniesieniu do podzbioru osobników starzejących się. Parametr dystrybucji czasowej charakteryzuje się tu podwyższonym wskaźnikiem skomplikowania, jako następstwo zwiększonego tempa deinkorporacji z zastosowaniem rozwiązań nieadopcyjnych, takich jak eutanazja lub specjalistyczna opieka terminalna.",
    "**Finding:** Physical appearance (Breed and Color) and Age are the strongest predictors of adoption, significantly outweighing the context of how an animal arrives (Intake Circumstances and Condition).": "**Postulat dedukcyjny:** Elementarne parametry predykcji fenotypowej (tj. kategoryzacja rasy i umaszczenie) deklasują czynniki związane stricte z tłem incydentu prowadzącego do przyjęcia schroniskowego (tzw. kody klasyfikacyjne zdarzeń). W połączeniu z wiekiem, dominują jako wiodący predyktor rezultatu wyjściowego.",
    "**Finding:** The COVID-19 pandemic period was associated with a marked increase in adoption rates and a reduction in total volume. These period shifts must be accounted for to prevent model drift.": "**Postulat dedukcyjny:** Wyznaczony kwantyl temporalny dla zaistnienia pandemii COVID-19, wskazał wyraźny wzrost absorpcji zjawisk adopcyjnych, pomimo regresji całkowitego wolumenu zarejestrowanych inkorporacji. Te dewiacje strukturalne populacji wymagają starannej mitygacji w estymatorze w trosce o rygor uniknięcia zjawiska concept drift (odchylenia pojęciowego modelu).",
    "**Global SHAP Feature Importance (Classification)**": "**Wyodrębnienie kluczowej hierarchii wpływów parametrów według dystrybucji w algorytmach SHAP (klasyfikator)**",
    "**Median Days to Outcome by Age**": "**Wartości mediany dla czasu ekspozycji wyznaczane wymiarem kategorii wiekowej (Age)**",
    "**Volume and Outcomes Across Periods**": "**Przekrojowa miara natężenia operacji wejściowych i deinkorporacji rozpatrywana na płaszczyznach historycznych**",
    "All generated thesis deliverables, target definitions, and validation reports are listed below.": "Dokument stanowi skondensowany indeks referencji powołujących się na wszystkie dedykowane zasoby badawcze (dossier) wytworzone przez pipeline analityczny włącznie z parametrami walidacyjnymi i konkluzjami testów empirycznych.",
    "Artifact Manifest": "Inwentarz Artefaktów Bazy",
    "Artifact Path": "Wyznaczona domena i ścieżka dostępu",
    "Artifact Type": "Rodzaj zarejestrowanego zasobu",
    "Automated euthanasia triaging": "Skryptowa automatyzacja decyzji eutanazyjnych (Triage)",
    "Best Use Case": "Wektor racjonalnej użyteczności (Best Practice)",
    "CatBoost consistently outperformed baseline models at separating adoptions from other outcomes, offering the highest precision-recall area under the curve (PR-AUC) for this imbalanced task.": "Zaimplementowana metoda klasyfikacji CatBoost konsekwentnie neutralizowała asymetryczną skuteczność modeli wyjściowych, dyskryminując w sposób najwłaściwszy procesy adopcyjne i generując bezkonkurencyjne pole dla ewaluacji metodą PR-AUC na mocno niezbilansowanym zbiorze docelowym.",
    "Chapter": "Pozycja Rozdziału",
    "Data only reflects intake time": "Parametryzacją wejściową objęto wyłącznie stany zarejestrowane adekwatnie z logiem czasowym początku obserwacji. Model ewaluacyjnie 'nie zna' późniejszych uwarunkowań adaptacyjnych osobnika w schronisku.",
    "Days": "Okres kwantyfikowany w domenie jednostek dziennych",
    "Exists": "Rozpoznany fizycznie",
    "For predicting the exact length of stay, CatBoost provided the lowest average error. However, length-of-stay is highly skewed and right-censored.": "Dla optymalizacji i predykcji surowej zmiennej ciągłej reprezentującej wymiar czasowy retencji, podejście estymacyjne na rdzeniu CatBoost wygenerowało najniższy współczynnik MAE. Koniecznym jest zaobsersem, że w ujęciu holistycznym zmienna ta ma mocno prawostronną deformację i ulega procesowi cenzurowania z tejże strony.",
    "Higher is better. Evaluated on out-of-time test set.": "Stymulacja optymalizacyjna przez maksymalizację. Badanie i ostateczna walidacja dokonana na chronologicznym kwantylu walidacyjnym (Out-of-time test set).",
    "Importance Impact": "Absolutny mnożnik korelacji i wpływu (Impact Magnitude)",
    "Lower is better. Mean absolute error on test set.": "Stymulacja optymalizacyjna przez minimalizację dysonansu (Mean Absolute Error). Badania zatwierdzone na kwantylu walidacyjnym w warunkach odciętej ewidencji.",
    "Model output is unavailable. Check model artifacts and metadata.": "Wyjście predykcyjne dla zadanych zapytań uległo zatrzymaniu brakiem danych. Zbadaj wektory artefaktów predyktora oraz jego metadane.",
    "No classification artifacts found.": "Dysk nie identyfikuje wyników estymacji dla problemu klasyfikacji.",
    "No model is perfect. Here is exactly where the model struggles and the magnitude of its errors:": "Ułomność strukturalna każdego systemu analitycznego wymusza obnażenie sektorów usterkowości. Oto dokładne zobrazowanie grup, w których estymator wykazuje wysoki stopień deficytu precyzji wraz ze skalowaniem rozmiaru dewiacji:",
    "No regression artifacts found.": "Dysk nie identyfikuje logów błędów ani metryk ewaluacyjnych modelu w trybie ciągłym (Regresji).",
    "Notes": "Obserwacje konkludujące",
    "Prediction failed.": "Proces propagacji dla wektora zapytań wejściowych zawiódł na warstwie błędu krytycznego.",
    "Primary Limitation": "Podstawowy element dymisji obiektywności (Limitation Limit)",
    "Primary Metric (MAE)": "Docelowy Wskaźnik Weryfikacji Optymalizacyjnej (MAE - Błąd Bezwzględny Zmiennej Ciągłej)",
    "Primary Metric (PR-AUC)": "Docelowy Wskaźnik Weryfikacji Optymalizacyjnej (PR-AUC - Czułość vs Precyzja względem Prawdopodobieństwa Klasyfikacyjnego)",
    "Prioritizing visibility campaigns": "Mechanizm asocjacyjno-heurystyczny dla dyskryminacji celów kampanii podbijających odnajdywalność społecznościową (Visibility Profiling)",
    "Read Thesis & Methodology Reports": "Odszukaj odnośnik do manuskryptu wraz z argumentacjami metodologicznymi i aparatami użytych pojęć.",
    "Refresh Data": "Resynchronizuj Bufory Pamięci Stanu (Refresh)",
    "Required": "Wyróżnik Krytyczności dla Wektorów Raportów Dyplomowych",
    "Riskiest Use Case": "Błędy poznawcze w implementacjach wysokiego szczebla krytycznego",
    "Run `python scripts/generate_diagnostics.py` to see error slices.": "Wykonaj skryptowy mechanizm `python scripts/generate_diagnostics.py` by zainicjować agregacje w rozbiciu na rzuty błędu predykcji.",
    "Run `python scripts/generate_evidence_pack.py` to see failure modes.": "Ewaluuj błędy z dekompozycją wykonując polecenie `python scripts/generate_evidence_pack.py` w konsoli uruchomieniowej.",
    "Source Script": "Mechanizm Wytwórczy (Źródłowy Kontroler Rutynowy)",
    "The machine learning pipeline evaluated logistic regression, random forests, histogram gradient boosting, and CatBoost models. Here is the final selection based on empirical validation data:": "Architektura badawcza systemu przeegzaminowała estymatory Regresji Logistycznej, Lasów Losowych, estymacje zoptymalizowane Histogramami Wzmacniania Gradientowego po implementacje wyższych rzędów optymalizacyjnych drzew kategorycznych, jakimi są mechanizmy rzędu CatBoost. Ustalenia zaprezentowane poniżej, dokonane są wyłącznie wehikułem wyodrębnionych procesów podzbiorów obarczonych atrybutem prawdy empirycznej z okresu zamkniętego:",
    "The regression model's Mean Absolute Error (MAE) varies drastically by subgroup:": "Miara uśrednionego błędu w trybie estymacji długości oczekiwania ma tendencję do drastycznej wariacji zależnie od identyfikacji kohorty:",
    "This dashboard translates raw shelter data into concrete evidence. Below are the finalized findings across the primary thesis hypotheses.": "Platforma udostępniona w tej przestrzeni pełni funkcję agregatora wnioskującego z wymiaru surowych danych ewidencyjnych po postulat dowodowy w ujęciu akademickim. Bezpośrednio pod komunikatem osadzono ostateczne ramy dowodowe odnoszące się do priorytetowych postulatów hipotez badawczych sformułowanych w obrębie dysertacji:",
    "Uses the combined classifier and regressor when advanced artifacts exist. This is a demo prediction, not a causal decision rule.": "Rutyna wymusza pobranie zasobów z potoku wytworzonego predyktora (skonsolidowany algorytm klasyfikująco-regresyjny). Narzędzie to stanowi symulację estymacyjną oraz weryfikację na żądanie i w żadnym ze swoich obiektywnych wskazań nie uprawnia do stanowienia niezależnej i odciętej reguły przyzwolenia na określoną decyzję fizyczną względem zjawiska.",
    "View Full Executive Summary Report": "Rozwiń dekompozycję całościowego ustępstwa wykonawczego dla streszczenia dysertacji",
    "When the model misclassifies an outcome, these are the most common failure modes:": "Dezintegracja struktury błędu i odchyleń predyktora. Pod spodem osadzono klasyfikatory najczęstszych dysonansów i omyłek estymatora w stosunku do obserwowalnej w przyszłości materii zdarzeniowej:",
    "While machine learning successfully ranks animals by placement difficulty, **these predictions are associative, not causal.**": "Konstrukty probabilistyczne poddawane treningowi na surowych danych statystycznych potwierdzają się w budowaniu wektorów rangujących, w aspekcie priorytetyzacji obciążeń adopcyjnych na zbiorach podmiotów. Pomimo tych możliwości **prezentowane ujęcia estymacyjne w całości obarczone są asocjacją cech, całkowicie wykluczając bezpośrednie domniemania kauzalne pomiędzy atrybutem podmiotu a generowaną w czasie przyszłym reakcją środowiska.**",
    "While puppies and kittens ('baby') often leave the shelter within 6-7 days, 'adult' animals face similar wait times. 'Senior' animals exhibit shorter median days to any outcome (e.g. 4.2 days), reflecting alternative outcome pathways. Age remains a critical predictive feature.": "Pomimo ewidentnego odchylenia obserwowalnego czasu opuszczenia stanowisk ewidencji przez grupę noworodkową rzędu do 7 jednostek (Dni), badana waga 'wielkości dorosłych' generuje wariancję czasową bardzo zbliżoną do tych pierwszych grup wiekowych. Najciekawsze odchylenia struktury modelu leżą w rzędzie kwantyli odzwierciedlonych wartością skróconą dla osobnika powyżej tzw. wieku geriatrycznego 'Senior'. Czas opuszczenia murów instytucji bywa tu niższy od standardowego (ok. 4 dni). Dyskrepancja jest powodowana ucieczką tych podmiotów od założeń procesu klasycznej opieki docelowej, co często zamyka te trajektorie wynikiem 'eutanazji' czy przymusu objęcia reżimową farmakoterapią poza ośrodkiem schroniskowym. Kryterium ontogenetyczne jest tym samym uznane za fundamentalną właściwość decyzyjno-różniczkową we wszystkich architekturach docelowych budowanych modeli.",
    "⚠️ Interpretation limits": "⚠️ Restrykcje poznawcze logiki asocjacyjnej dla wymiarów interpretacyjnych",
    "🎓 Thesis Conclusions": "🎓 Zbiór finalnych dedukcji oraz implikacji",
    "This explanation shows model feature contributions, not real-world causes of this animal's outcome. Feature families like breed or coat color represent associations in the training set, not proof of direct impact.": "Zobrazowana mapa sił napędowych dekomponuje składowe macierzy i ich nacisk punktowy we wnętrzu architektury. Nie należy ich absolutnie powiązywać lub dokonywać uproszczeń redukując w naturalne związki przyczynowo-skutkowe charakteryzujące otaczający świat empiryczny i reakcję ludzi w fizycznym ośrodku adopcyjnym. Oś wektora cech taka jak przynależność formalno-taksonomiczna bądź estetyka umaszczenia odzwierciedla tu twardo korelacyjną statystykę macierzy zbiorów historycznych (Dane uczące modelu) w izolacji do postulatów by stanowiły one obiektywne oddziaływanie bezpośrednie (Impact)."
}

for k, v in replacements.items():
    if k in new_PL:
        new_PL[k] = v

import pprint
new_pl_str = pprint.pformat(new_PL, indent=4, sort_dicts=False)
new_pl_str = "PL = " + new_pl_str

new_content = content.replace("PL = " + pl_str, new_pl_str)

with open(file_path, 'w', encoding='utf-8') as f:
    f.write(new_content)

print("PL dictionary updated successfully.")
